# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2
jobs:
    build:
        docker:
            # - image: cibuilds/hugo:latest
            - image: aagnone/circleci-hugo:latest
        environment:
            HUGO_BUILD_DIR: /opt/hugo/public
        steps:
            - checkout

            # # Download and cache dependencies
            # - restore_cache:
            #     keys:
            #       - v1-dependencies-{{ checksum "requirements.txt" }}
            #       # fallback to using the latest cache if no exact match is found
            #       - v1-dependencies-

            - run: git submodule sync && git submodule update --init

            # - save_cache:
            #     paths:
            #       - ./venv
            #     key: v1-dependencies-{{ checksum "requirements.txt" }}

            - run:
                name: Install dependencies
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r syndication/src/requirements.txt
            - run:
                name: Local build
                command: |
                    HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
            - run:
                name: Pre-verification
                command: |
                    htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html --empty-alt-ignore --disable-external
                    . venv/bin/activate
                    bash .circleci/blog_syndication.sh
            - run:
                name: Blog post syndication
                command: |
                    echo "skip"
                    . venv/bin/activate
                    # bash .circleci/blog_syndication.sh
            - run:
                name: run tests
                command: |
                    . venv/bin/activate
                    echo "Tests here"

    deploy:
        docker:
            # - image: cibuilds/hugo:latest
            - image: aagnone/circleci-hugo:latest
        steps:
            - checkout

            - run:
                name: install dependencies
                command: |
                    . venv/bin/activate
                    pip install -r syndication/src/requirements.txt
                    sudo apt-get update && sudo apt-get install -y rsync vim hugo

            - run:
                  name: Deploy to website
                  command: |
                      . venv/bin/activate
                      bash .circleci/blog_syndication.sh

            - store_artifacts:
                path: deploy.log

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
                  # only deploy from the master branch
                  filters:
                      branches:
                          only: master
