# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2
jobs:
    build:
        docker:
            - image: aagnone/circleci-hugo:latest
              user: user
        steps:
            - checkout
            - run:
                name: Blog post syndication
                command: |
                    echo "Syndication step"
                    bash .circleci/blog_syndication.sh 2>&1 | tee deploy.log
            - store_artifacts:
                path: deploy.log
workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
