# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2
jobs:
    build:
        docker:
            - image: aagnone/circleci-hugo:latest
              user: user
        environment:
            HUGO_BUILD_DIR: /home/user/public
        steps:
            - checkout
            - run: git submodule sync && git submodule update --init
            - run:
                name: Local build
                command: |
                    HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
            - run:
                name: Pre-verification
                command: |
                    echo Not running htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html --empty-alt-ignore --disable-external
            - run:
                name: Blog post syndication
                command: |
                    echo "Syndication step"
                    bash .circleci/blog_syndication.sh
            - store_artifacts:
                path: deploy.log
workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
